syntax = "proto3";

package spectrum;

service StorageNode {
  rpc BeginAttachableTransaction(BeginAttachableTransactionRequest) returns (BeginAttachableTransactionResponse) {}
  rpc EndAttachableTransaction(EndAttachableTransactionRequest) returns (EndAttachableTransactionResponse) {}

  rpc UpdateMetadata(UpdateMetadataRequest) returns (UpdateMetadataResponse) {}
  rpc AcquireMetadataLock(AcquireMetadataLockRequest) returns (AcquireMetadataLockResponse) {}
  rpc UpgradeMetadataLock(UpgradeMetadataLockRequest) returns (UpgradeMetadataLockResponse) {}
  rpc ReleaseMetadataLock(ReleaseMetadataLockRequest) returns (ReleaseMetadataLockResponse) {}
  rpc ReleaseMetadataLocks(ReleaseMetadataLocksRequest) returns (ReleaseMetadataLocksResponse) {}

  rpc CreateTable(CreateTableRequest) returns (CreateTableResponse) {}
  rpc DeleteTable(DeleteTableRequest) returns (DeleteTableResponse) {}
  rpc LockTable(LockTableRequest) returns (LockTableResponse) {}
  rpc UnlockTable(UnlockTableRequest) returns (UnlockTableResponse) {}
  rpc CloseTable(CloseTableRequest) returns (CloseTableResponse) {}

  rpc PostDDL(PostDDLRequest) returns (PostDDLResponse) {}

  rpc InitIndex(InitIndexRequest) returns (InitIndexResponse) {} 
  rpc InitRnd(InitRndRequest) returns (InitRndResponse) {} 
  rpc EndIndex(EndIndexRequest) returns (EndIndexResponse) {} 
  rpc EndRnd(EndRndRequest) returns (EndRndResponse) {} 

  rpc ReadRow(ReadRowRequest) returns (ReadRowResponse) {} 
  rpc ReadNextRow(ReadNextRowRequest) returns (ReadNextRowResponse) {} 
  rpc ReadPrevRow(ReadPrevRowRequest) returns (ReadPrevRowResponse) {} 
  rpc WriteRow(WriteRowRequest) returns (WriteRowResponse) {} 
  rpc UpdateRow(UpdateRowRequest) returns (UpdateRowResponse) {} 
  rpc DeleteRow(DeleteRowRequest) returns (DeleteRowResponse) {} 
  rpc Commit(CommitRequest) returns (CommitResponse) {} 

  rpc ReplicateRow(ReplicateRowRequest) returns (ReplicateRowResponse) {} 
}

service StorageReplicaNode {
  rpc Replicate (stream ReplicateRequest) returns (stream ReplicateResponse);
}

message SystemVariables {
  int64 option_bits = 1;
}

message Thread {
  int64 id = 1;
  int32 tx_isolation = 2;
  int32 sql_command = 3;
  SystemVariables system_variables = 4;
}

message Row {
  bytes record = 1;
  int32 record_length = 2;
  repeated Field fields = 3;
}

message Field {
  string name = 1;
  bytes value = 2;
  bool is_null = 3;
}

message UpdateMetadataRequest {
  Thread thread = 1;
  string table = 2;
  uint64 object_id = 3;
  string object_name = 4;
}

message UpdateMetadataResponse {
}

message AcquireMetadataLockRequest {
  Thread thread = 1;
  int32 namespace = 2;
  string schema = 3;
  string table = 4;
  string column = 5;
  int32 type = 6;
  int32 duration = 7;
  int32 ticket_number = 8;
}

message AcquireMetadataLockResponse {
}

message UpgradeMetadataLockRequest {
  Thread thread = 1;
  int32 duration = 2;
  int32 ticket_number = 3;
  int32 new_type = 4;
}

message UpgradeMetadataLockResponse {
}

message ReleaseMetadataLockRequest {
  Thread thread = 1;
  int32 duration = 2;
  int32 ticket_number = 3;
}

message ReleaseMetadataLockResponse {
}

message ReleaseMetadataLocksRequest {
  Thread thread = 1;
  bool transactional = 2;
}

message ReleaseMetadataLocksResponse {
}

message CreateTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
}

message CreateTableResponse {
}

message DeleteTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  string table_path = 4;
}

message DeleteTableResponse {
}

message LockTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  bool start_stmt = 7;
}

message LockTableResponse {
}

message UnlockTableResponse {
}

message UnlockTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
}

message CloseTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
}

message CloseTableResponse {
}

message PostDDLRequest {
  Thread thread = 1;
}

message PostDDLResponse {
}

message InitIndexRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  int32 index = 7;
}

message InitIndexResponse {
}

message EndIndexRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
}

message EndIndexResponse {
}

message InitRndRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  bool scan = 7;
}

message InitRndResponse {
}

message EndRndRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
}

message EndRndResponse {
}

message ReadRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  int32 index = 7;
  bytes key = 8;
  int32 key_len = 9;
  int32 find_flag = 10;
  int32 init = 11;
  bool init_scan = 12;
}

message ReadRowResponse {
  Row row = 1;
}

message ReadNextRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  int32 index = 7;
  int32 same = 8;
  int32 init = 9;
  bool init_scan = 10;
}

message ReadNextRowResponse {
  Row row = 1;
}

message ReadPrevRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  int32 index = 7;
  int32 init = 8;
  bool init_scan = 9;
}

message ReadPrevRowResponse {
  Row row = 1;
}

message WriteRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  Row row = 7;
  bool autoinc_field_has_explicit_non_null_value = 8;
}

message WriteRowResponse {
  Row row = 1;
  int64 insert_id = 2;
}

message UpdateRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  Row new_row = 7;
  Row old_row = 8;
  bool autoinc_field_has_explicit_non_null_value = 9;
}

message UpdateRowResponse {
}

message DeleteRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  Row row = 7;
}

message DeleteRowResponse {
}

message CommitRequest {
  Thread thread = 1;
  bool all = 2;
  bool ignore_global_read_lock = 3;
}

message CommitResponse {
}

message BeginAttachableTransactionRequest {
  Thread thread = 1;
  bool readonly = 2;
}

message BeginAttachableTransactionResponse {
}

message EndAttachableTransactionRequest {
  Thread thread = 1;
}

message EndAttachableTransactionResponse {
}

message ReplicateRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 lock_action = 6;
  Row new_row = 7;
  Row old_row = 8;
}

message ReplicateRowResponse {
}

message ReplicateRequest {
  uint64 event_id = 1;
  oneof event {
    CreateTableRequest create_table_event = 2;
    DeleteTableRequest delete_table_event = 3;
    PostDDLRequest post_ddl_event = 4;
    UpdateMetadataRequest update_metadata_event = 5;
    ReplicateRowRequest replicate_row_event = 6;
    CommitRequest commit_event = 7;
  }
}

message ReplicateResponse {
  uint64 event_id = 1;
}