syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.spectrum.grpc";
option java_outer_classname = "HelloWorldProto";
option objc_class_prefix = "HLW";

package spectrum;

service HeadNode {
  rpc Propose (DataItemMessage) returns (DataItemMessage) {}
}

service StorageNode {
  rpc CreateTable(CreateTableRequest) returns (CreateTableResponse) {}
  rpc LockTable(LockTableRequest) returns (LockTableResponse) {}
  rpc UnlockTable(UnlockTableRequest) returns (UnlockTableResponse) {}
  rpc InitIndex(InitIndexRequest) returns (InitIndexResponse) {} 
  rpc InitRnd(InitRndRequest) returns (InitRndResponse) {} 
  rpc EndIndex(EndIndexRequest) returns (EndIndexResponse) {} 
  rpc EndRnd(EndRndRequest) returns (EndRndResponse) {} 

  rpc ReadRow(ReadRowRequest) returns (ReadRowResponse) {} 
  rpc ReadNextRow(ReadNextRowRequest) returns (ReadNextRowResponse) {} 
  rpc ReadPrevRow(ReadPrevRowRequest) returns (ReadPrevRowResponse) {} 
  rpc WriteRow(WriteRowRequest) returns (WriteRowResponse) {} 
  rpc UpdateRow(UpdateRowRequest) returns (UpdateRowResponse) {} 
  rpc Commit(CommitRequest) returns (CommitResponse) {} 

  rpc CreateReplica (CreateReplicaRequestMessage) returns (CreateReplicaResponseMessage) {}
  rpc UpdateEpoch (UpdateEpochRequestMessage) returns (UpdateEpochResponseMessage) {}

  rpc Prepare (PrepareRequestMessage) returns (PrepareResponseMessage) {}
  rpc Accept (AcceptRequestMessage) returns (AcceptResponseMessage) {}
  rpc Abort (AbortRequestMessage) returns (AbortResponseMessage) {}
}

message SystemVariables {
  int64 option_bits = 1;
}

message Thread {
  repeated MDL mdl_list = 1;
  SystemVariables system_variables = 2;
}

message MDL {
  int32 namespace = 1;
  string schema = 2;
  string table = 3;
  string column = 4;
  int32 type = 5;
  int32 duration = 6;
}

message Row {
  bytes record = 1;
  int32 record_length = 2;
  repeated Field fields = 3;
}

message Field {
  string name = 1;
  bytes value = 2;
  bool is_null = 3;
}

message CreateTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
}

message CreateTableResponse {
}

message LockTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
}

message UnlockTableResponse {
}

message UnlockTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
}

message LockTableResponse {
}

message InitIndexRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
  int32 index = 5;
}

message InitIndexResponse {
}

message EndIndexRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
}

message EndIndexResponse {
}

message InitRndRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
  bool scan = 5;
}

message InitRndResponse {
}

message EndRndRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
}

message EndRndResponse {
}

message ReadRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
  int32 index = 5;
  bytes key = 6;
  int32 key_len = 7;
  int32 find_flag = 8;
  int32 init = 9;
  bool init_scan = 10;
}

message ReadRowResponse {
  Row row = 1;
}

message ReadNextRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
  int32 index = 5;
  int32 same = 6;
  int32 init = 7;
  bool init_scan = 8;
}

message ReadNextRowResponse {
  Row row = 1;
}

message ReadPrevRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
  int32 index = 5;
  int32 init = 6;
  bool init_scan = 7;
}

message ReadPrevRowResponse {
  Row row = 1;
}

message WriteRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
  Row row = 5;
  bool autoinc_field_has_explicit_non_null_value = 6;
}

message WriteRowResponse {
  int64 insert_id = 1;
}

message UpdateRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int32 lock_type = 4;
  Row new_row = 5;
  Row old_row = 6;
  bool autoinc_field_has_explicit_non_null_value = 7;
}

message UpdateRowResponse {
}

message CommitRequest {
  Thread thread = 1;
  bool all = 2;
  bool ignore_global_read_lock = 3;
}

message CommitResponse {
}












message CreateReplicaRequestMessage {
  string namespace = 1;
  int32 replicaId = 2;
}

message CreateReplicaResponseMessage {
  string acceptorId = 1;
}

message UpdateEpochRequestMessage {
  string namespace = 1;
  int32 replicaId = 2;
  int64 epoch = 3;
}

message UpdateEpochResponseMessage {
  int64 epoch = 1;
}

message DataItemMessage {
  string namespace = 1;
  string key = 2;
  optional string value = 3;
  optional bool isNext = 4;
  int64 version = 5;
}

message ProposalMessage {
  string key = 1;
  optional string value = 2;
  optional bool isNext = 3;
  int64 version = 4;
  int64 sequenceNumber = 5;
  optional ProposalMessage parentProposal = 6;
}

message PrepareRequestMessage {
  string acceptorId = 1;
  int64 epoch = 2;
  ProposalMessage proposal = 3;
}

message PrepareResponseMessage {
  bool prepared = 1;
  ProposalMessage preparedProposal = 2;
  ProposalMessage acceptedProposal = 3;
  int64 epoch = 4;
  int64 maxSequenceNumber = 5;
}

message AcceptRequestMessage {
  string acceptorId = 1;
  int64 epoch = 2;
  ProposalMessage proposal = 3;
}

message AcceptResponseMessage {
  bool accepted = 1;
  ProposalMessage preparedProposal = 2;
  ProposalMessage acceptedProposal = 3;
  int64 epoch = 4;
  int64 maxSequenceNumber = 5;
}

message AbortRequestMessage {
  string acceptorId = 1;
  ProposalMessage proposal = 2;
}

message AbortResponseMessage {
}
