syntax = "proto3";

package spectrum;

service StorageNode {
  rpc BeginAttachableTransaction(BeginAttachableTransactionRequest) returns (BeginAttachableTransactionResponse) {}
  rpc EndAttachableTransaction(EndAttachableTransactionRequest) returns (EndAttachableTransactionResponse) {}

  rpc AcquireMetadataLock(AcquireMetadataLockRequest) returns (AcquireMetadataLockResponse) {}
  rpc ReleaseMetadataLock(ReleaseMetadataLockRequest) returns (ReleaseMetadataLockResponse) {}

  rpc CreateTable(CreateTableRequest) returns (CreateTableResponse) {}
  rpc LockTable(LockTableRequest) returns (LockTableResponse) {}
  rpc UnlockTable(UnlockTableRequest) returns (UnlockTableResponse) {}
  rpc InitIndex(InitIndexRequest) returns (InitIndexResponse) {} 
  rpc InitRnd(InitRndRequest) returns (InitRndResponse) {} 
  rpc EndIndex(EndIndexRequest) returns (EndIndexResponse) {} 
  rpc EndRnd(EndRndRequest) returns (EndRndResponse) {} 

  rpc ReadRow(ReadRowRequest) returns (ReadRowResponse) {} 
  rpc ReadNextRow(ReadNextRowRequest) returns (ReadNextRowResponse) {} 
  rpc ReadPrevRow(ReadPrevRowRequest) returns (ReadPrevRowResponse) {} 
  rpc WriteRow(WriteRowRequest) returns (WriteRowResponse) {} 
  rpc UpdateRow(UpdateRowRequest) returns (UpdateRowResponse) {} 
  rpc DeleteRow(DeleteRowRequest) returns (DeleteRowResponse) {} 
  rpc Commit(CommitRequest) returns (CommitResponse) {} 

  rpc ReplicateRow(ReplicateRowRequest) returns (ReplicateRowResponse) {} 

}

message SystemVariables {
  int64 option_bits = 1;
}

message Thread {
  int64 id = 1;
  SystemVariables system_variables = 2;
}

message Row {
  bytes record = 1;
  int32 record_length = 2;
  repeated Field fields = 3;
}

message Field {
  string name = 1;
  bytes value = 2;
  bool is_null = 3;
}

message AcquireMetadataLockRequest {
  Thread thread = 1;
  int32 namespace = 2;
  string schema = 3;
  string table = 4;
  string column = 5;
  int32 type = 6;
  int32 duration = 7;
  int32 ticket_number = 8;
}

message AcquireMetadataLockResponse {
}

message ReleaseMetadataLockRequest {
  Thread thread = 1;
  int32 duration = 2;
  int32 ticket_number = 3;
}

message ReleaseMetadataLockResponse {
}

message CreateTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
}

message CreateTableResponse {
}

message LockTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  bool start_stmt = 6;
}

message UnlockTableResponse {
}

message UnlockTableRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
}

message LockTableResponse {
}

message InitIndexRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 index = 6;
}

message InitIndexResponse {
}

message EndIndexRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
}

message EndIndexResponse {
}

message InitRndRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  bool scan = 6;
}

message InitRndResponse {
}

message EndRndRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
}

message EndRndResponse {
}

message ReadRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 index = 6;
  bytes key = 7;
  int32 key_len = 8;
  int32 find_flag = 9;
  int32 init = 10;
  bool init_scan = 11;
}

message ReadRowResponse {
  Row row = 1;
}

message ReadNextRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 index = 6;
  int32 same = 7;
  int32 init = 8;
  bool init_scan = 9;
}

message ReadNextRowResponse {
  Row row = 1;
}

message ReadPrevRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  int32 index = 6;
  int32 init = 7;
  bool init_scan = 8;
}

message ReadPrevRowResponse {
  Row row = 1;
}

message WriteRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  Row row = 6;
  bool autoinc_field_has_explicit_non_null_value = 7;
}

message WriteRowResponse {
  Row row = 1;
  int64 insert_id = 2;
}

message UpdateRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  Row new_row = 6;
  Row old_row = 7;
  bool autoinc_field_has_explicit_non_null_value = 8;
}

message UpdateRowResponse {
}

message DeleteRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  Row row = 6;
}

message DeleteRowResponse {
}

message CommitRequest {
  Thread thread = 1;
  bool all = 2;
  bool ignore_global_read_lock = 3;
}

message CommitResponse {
}

message BeginAttachableTransactionRequest {
  Thread thread = 1;
  bool readonly = 2;
}

message BeginAttachableTransactionResponse {
}

message EndAttachableTransactionRequest {
  Thread thread = 1;
}

message EndAttachableTransactionResponse {
}

message ReplicateRowRequest {
  Thread thread = 1;
  string database = 2;
  string table = 3;
  int64 handler = 4;
  int32 lock_type = 5;
  Row new_row = 6;
  Row old_row = 7;
}

message ReplicateRowResponse {
}
