SPECTRUM_NODE_ID=${1}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MYSQL_SPECTRUM_ROOT=${SCRIPT_DIR}/../build
MYSQL_SPECTRUM_NODE_DATA_ROOT=${MYSQL_SPECTRUM_ROOT}/mysql-spectrum-data/${SPECTRUM_NODE_ID}

mkdir -p ${MYSQL_SPECTRUM_NODE_DATA_ROOT}
${MYSQL_SPECTRUM_ROOT}/bin/mysqld --initialize-insecure --datadir=${MYSQL_SPECTRUM_NODE_DATA_ROOT}

