MYSQL_SPECTRUM_COMPUTE_ID="${1:-0}"
MYSQL_SPECTRUM_ROOT=/Users/gupeng/workplace/mysql-server/build/mysql-spectrum
MYSQL_SPECTRUM_COMPUTE_DATA_ROOT=/Users/gupeng/mysql-spectrum-data/compute-${MYSQL_SPECTRUM_COMPUTE_ID}
MYSQL_SPECTRUM_COMPUTE_PORT=$(expr 3306 + ${MYSQL_SPECTRUM_COMPUTE_ID})
MYSQL_SPECTRUM_COMPUTE_SOCK=/tmp/mysql-spectrum-compute-${MYSQL_SPECTRUM_COMPUTE_ID}.sock

export SPECTRUM_COMPUTE_NODE=TRUE
${MYSQL_SPECTRUM_ROOT}/bin/mysqld --console --log-error-verbosity=3 --socket=${MYSQL_SPECTRUM_COMPUTE_SOCK} --port=${MYSQL_SPECTRUM_COMPUTE_PORT} --datadir=${MYSQL_SPECTRUM_COMPUTE_DATA_ROOT}

